### ISSUE TITLE
document connection issues to ATEM

### ISSUE THREAD

**Issue by czenker** [wifi-tally/wifi-tally#16]
https://forum.blackmagicdesign.com/viewtopic.php?f=4&t=101841

**Comment by kubikrubik21** [comment]
Yesterday was my first test with v0.1-alpha4 at the Atem mixer. I started the hub, selected Atem with correct IP, but it doesn't connect to the mixer.

The problem was, that too many clients were already connected to the mixer. About 5 connections.

I restarted everything and it worked perfectly. Hub and Atem were connected. 4 Tallys were connected and showed the correct channel.
