### ISSUE TITLE
LED glowing green in "OnRelease" state

### ISSUE THREAD

**Issue by kubikrubik21** [wifi-tally/wifi-tally#33]
I have noticed that my LED was glowing light green in **onRelease** state. Is it what it should be??? Because I was expecting the LED to turn off in this state.

my-led.lua Line 144
`onRelease = flashPattern(".", colors.GREEN, nil, false),`

That means 1% Duty cycle at 1kHz PWM frequency. Thats enough to let the LED glow.

**Comment by czenker** [comment]
Yes, this is intentional and was added in 0.1-alpha3 (see #7).

I had the issue that our camera operators did not trust the hardware as much as I did. :laughing: So they sometimes were not sure if there is something wrong with the tally or not. Adding the very dim green light should be clearly distinguishable from the preview state and gives them peace of mind.

**Comment by kubikrubik21** [comment]
Makes sense. Thank you for clearing that up 😉
