### ISSUE TITLE
Operator Light Brightness

### ISSUE THREAD

**Issue by ruudboon** [wifi-tally/wifi-tally#57]
In theaters I noticed that 20% sometimes is even too bright.
Can we allow to go to 1%? Or to create consistency even go to off like the stage light?

**Comment by czenker** [comment]
LEDs and their non-linear dim curve... :laughing: I don't see a problem with decreasing that value.

I would rather not allow to turn the operator light off completely. The Tally should be beginners friendly and turning the operator light off by accident might be very confusing, because the Tally might seem broken. On the other hand I do not see a reason why anyone would want to turn off the operator light completly. As a workaround... any production should have some Gaffer Tape, right? :wink:

**Comment by ruudboon** [comment]
1% works for me. Thnx
